# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: khanhtcp
google_analytics: khanhtcp
title: khanhtcp

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: khanhtcp

description: Khanhtcp's website
author:
  name: "Khantcp - Stay hungry stay foolish."
  email: topol.phukhanh@gmail.com
  github: topolphukhanh
#  twitter: tcpkhanh
#  pinterest: asd123
  linkedin: trancongphukhanh
  facebook: trancongphukhanh
  bio: To be honest, I'm having some trouble remembering right now, so why don't you just watch Naruto movie and it will answer all your questions.
  email_md5: a29870450f302ac9a16cf612f53cedc9

#rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
#sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
